import os
import subprocess

from cupti_build import build as cupti_build_func


def generate_git_version_file():
    """
    Retrieves the current git hash and writes it to _git_info.py
    inside the package directory.
    """
    git_hash = "unknown"
    try:
        # Check if inside a git repository
        git_hash = subprocess.check_output(
            ["git", "rev-parse", "HEAD"], 
            stderr=subprocess.DEVNULL
        ).decode("utf-8").strip()
    except (subprocess.CalledProcessError, FileNotFoundError, OSError):
        pass # Remain "unknown" if git is not available (e.g., install from tarball)

    # Path to where the file should be generated
    # Adjust this if your package structure is different, but based on your toml:
    output_dir = os.path.join("src", "nvidia_resiliency_ext")
    output_file = os.path.join(output_dir, "_git_info.py")
    
    # Ensure directory exists (it should, but safety first)
    if os.path.exists(output_dir):
        with open(output_file, "w") as f:
            f.write(f'# This file is automatically generated by cupti_build.py\n')
            f.write(f'GIT_COMMIT_HASH = "{git_hash[:7]}"\n')


def build(setup_kwargs):
    # 1. ALWAYS generate the git hash file, even if skipping extension build
    generate_git_version_file()

    # 2. Proceed with CUPTI extension build
    cupti_build_func(setup_kwargs)
