#!/bin/bash

#SBATCH --account=root
#SBATCH --partition=gb-nvl-134-135
#SBATCH --time=00:30:00

#SBATCH --job-name=llama4-scout-gb200
#SBATCH --output=/tmp/slurm-%j.launch.out
#SBATCH --error=/tmp/slurm-%j.launch.err

#SBATCH --nodes=2
#SBATCH --ntasks-per-node=4
#SBATCH --gpus-per-node=4
#SBATCH --exclusive
#SBATCH --mem=0

log_msg() {
    local msg="$1"
    UNIX_DATETIME=$(date +%s)
    HUMAN_DATETIME=$(date -d "@$UNIX_DATETIME" '+%Y-%m-%d %H:%M:%S.%3N')
    echo ">>> ${msg} ${UNIX_DATETIME} (${HUMAN_DATETIME})"
}

log_msg "START SBATCH"
echo "Running on nodes: ${SLURM_NODELIST}"
export RITS_PLATFORM_TYPE=gb200
export RITS_GPUS_PER_NODE=4
export RITS_NVL_DOMAIN_SIZE=72
export NCCL_IB_DISABLE=0
export NCCL_NET_GDR_LEVEL=3
export RITS_CLUSTER_NAME=nvl72
export PYXIS_LOG_LEVEL=debug
export NCCL_IB_SL=1
export NCCL_IB_TIMEOUT=19
export UB_TIMEOUT=720
export CUDA_DEVICE_MAX_CONNECTIONS=1
export NVTE_FWD_LAYERNORM_SM_MARGIN=16
export NVTE_BWD_LAYERNORM_SM_MARGIN=16
export NCCL_P2P_NET_CHUNKSIZE=2097152
export NCCL_DEBUG=WARN
export PYTHONUNBUFFERED=1
export ONE_LOGGER_JOB_CATEGORY=test
export LOGLEVEL=DEBUG
export TORCHINDUCTOR_WORKER_START=fork
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
export TORCH_CPP_LOG_LEVEL=INFO
export TORCH_NCCL_TRACE_BUFFER_SIZE=2000
export TORCH_NCCL_RETHROW_CUDA_ERRORS=0
export TORCH_NCCL_ENABLE_MONITORING=1
export TORCH_NCCL_DUMP_ON_TIMEOUT=1
export TORCH_NCCL_LOG_CPP_STACK_ON_UNCLEAN_SHUTDOWN=0
export TORCH_NCCL_HEARTBEAT_TIMEOUT_SEC=20
export TORCH_DIST_INIT_BARRIER=0
export TORCH_INCLUDE_STACK_TRACE=0
export TORCH_INCLUDE_ONLY_ACTIVE=1
export TORCH_NCCL_EXTRA_DUMP_ON_EXEC=1

# Checkpoint settings (overridable via sbatch --export)
export DIST_TIMEOUT_AFTER_INIT="${DIST_TIMEOUT_AFTER_INIT:-1800}"
# USE_ASYNC_CKPT=1: enable async checkpointing every CKPT_SAVE_INTERVAL iters
export USE_ASYNC_CKPT="${USE_ASYNC_CKPT:-0}"
export CKPT_SAVE_INTERVAL="${CKPT_SAVE_INTERVAL:-100}"
export USE_CPU_SHM="${USE_CPU_SHM:-1}"

# Quantization mode (overridable via sbatch --export)
export USE_FP8="${USE_FP8:-1}"
export USE_FP4="${USE_FP4:-0}"

# Overlap comm (overridable via sbatch --export)
export USE_OVERLAP_COMM="${USE_OVERLAP_COMM:-0}"

# Node / task geometry (SLURM_NNODES is set by SLURM from --nodes override)
export GPUS_PER_NODE="${GPUS_PER_NODE:-4}"
TOTAL_TASKS=$((SLURM_NNODES * GPUS_PER_NODE))

# Per-experiment output directory (overridable via sbatch --export)
export BASE_EXPERIMENTS_DIR="${BASE_EXPERIMENTS_DIR:-/home/sbak/experiments/llama4-scout-gb200}"
export EXPERIMENT_DIR="${EXPERIMENT_DIR:-${BASE_EXPERIMENTS_DIR}/ckpt_test/n${SLURM_NNODES}}"

mkdir -p ${BASE_EXPERIMENTS_DIR}/datacache
mkdir -p ${EXPERIMENT_DIR}/tensorboard

: "${SLURM_RESTART_COUNT:=0}"

LOG_DIR=${EXPERIMENT_DIR}/logs
mkdir -p ${LOG_DIR}
echo "Writing logs to ${LOG_DIR}"
LOG_FILE_BASE="${LOG_DIR}/slurm/${SLURM_JOB_ID}.${SLURM_RESTART_COUNT}"

# ── Shared-tmp directory (NFS, for cross-srun-step communication) ─────────────
# Mounted to /shared_tmp (NOT /tmp) so the container keeps its native fast /tmp.
SHARED_TMP_HOST=/home/sbak/tmp/${SLURM_JOB_ID}
mkdir -p ${SHARED_TMP_HOST}

# ── Pre-populate .myenv with all variables that must reach the container ───────
# Pyxis env forwarding is unreliable for vars set via sbatch --export; writing
# them into .myenv guarantees the inner bash picks them up via `source`.
MYENV_FILE=${SHARED_TMP_HOST}/.myenv_${SLURM_JOB_ID}.sh
cat > ${MYENV_FILE} << MYENVEOF
# Auto-generated by l4_gb200_reduced.sh — do not edit by hand.
export DIST_TIMEOUT_AFTER_INIT=${DIST_TIMEOUT_AFTER_INIT}
export USE_ASYNC_CKPT=${USE_ASYNC_CKPT}
export CKPT_SAVE_INTERVAL=${CKPT_SAVE_INTERVAL}
export USE_CPU_SHM=${USE_CPU_SHM}
export USE_FP8=${USE_FP8}
export USE_FP4=${USE_FP4}
export USE_OVERLAP_COMM=${USE_OVERLAP_COMM}
# Prepend local nvrx src so container picks up our changes without a pip install step.
export PYTHONPATH=/home/sbak/nvidia-resiliency-ext/src:\${PYTHONPATH}
MYENVEOF

# Mounts
LUSTRE=/home:/home
SHARED_TMP=${SHARED_TMP_HOST}:/shared_tmp
LOGS=${EXPERIMENT_DIR}/logs:/logs
MEGATRON_REPO=/home/sbak/megatron-lm-main:/megatron-lm_repo
DATACACHE=${BASE_EXPERIMENTS_DIR}/datacache:/datacache
TENSORBOARD=${EXPERIMENT_DIR}/tensorboard:/tensorboard
WORKSPACE=/home/sbak/tmp:/workspace
FR_DUMP=${EXPERIMENT_DIR}/flight_recorder:/flight_recorder
mkdir -p ${EXPERIMENT_DIR}/flight_recorder
CONTAINER_MOUNTS=$LUSTRE,$SHARED_TMP,$LOGS,$MEGATRON_REPO,$DATACACHE,$TENSORBOARD,$WORKSPACE,$FR_DUMP

# ── Disk cleanup: remove stale enroot containers from prior jobs ──────────────
log_msg "START disk_cleanup"
srun \
    --label \
    --ntasks-per-node=1 \
    --ntasks=${SLURM_NNODES} \
    --kill-on-bad-exit=0 \
    --mpi=none \
    bash -c '
        ENROOT_DIR="/var/lib/enroot/data/$(id -u)"
        rm -rf "${ENROOT_DIR:?}"/* 2>/dev/null || true
        echo "$(hostname): / $(df -h / | tail -1 | awk "{print \$3\" used, \"\$4\" avail\"}")"
    '
log_msg "END disk_cleanup"

# all node setup
#--------------------------------
log_msg "START all_node_setup"
srun \
    --label \
    --container-mounts ${CONTAINER_MOUNTS} \
    --container-image /home/sbak/mcore_ci_0415.sqsh \
    --container-name ${SLURM_JOB_ID} \
    --container-workdir / \
    --exclusive \
    --error=${LOG_FILE_BASE}.0.all_node_setup.log \
    --output=${LOG_FILE_BASE}.0.all_node_setup.log \
    --ntasks-per-node=1 \
    --ntasks=${SLURM_NNODES} \
    --kill-on-bad-exit=0 \
    --mpi=none \
    bash -c '
        # Use a per-node NFS path so all ranks on each node find the right clone.
        MEGATRON_PATH=/shared_tmp/megatron_$(hostname)_${SLURM_JOB_ID}
        mkdir -p ${MEGATRON_PATH}
        pushd $MEGATRON_PATH
        CURRENT_BRANCH=$(git -C /megatron-lm_repo branch --show-current)
        echo "Cloning Megatron branch $CURRENT_BRANCH to ${MEGATRON_PATH}"
        git clone --single-branch --branch $CURRENT_BRANCH /megatron-lm_repo .
        popd
    '
log_msg "END all_node_setup"

# main workload
#--------------------------------
log_msg "START main_workload"
srun \
    --label \
    --container-mounts ${CONTAINER_MOUNTS} \
    --container-image /home/sbak/mcore_ci_0415.sqsh \
    --container-name ${SLURM_JOB_ID} \
    --container-workdir / \
    --error=${LOG_FILE_BASE}.1.main_workload.log \
    --output=${LOG_FILE_BASE}.1.main_workload.log \
    --ntasks-per-node=${GPUS_PER_NODE} \
    --ntasks=${TOTAL_TASKS} \
    --kill-on-bad-exit=0 \
    --mpi=none \
    bash -c '
        source /shared_tmp/.myenv_${SLURM_JOB_ID}.sh

        # Match the per-node path used in all_node_setup.
        MEGATRON_PATH=/shared_tmp/megatron_$(hostname)_${SLURM_JOB_ID}

        NFS_TRITON_CACHE=/home/sbak/experiments/llama4-scout-gb200/triton_cache
        NFS_INDUCTOR_CACHE=/home/sbak/experiments/llama4-scout-gb200/inductor_cache

        # Per-rank Triton/inductor cache on the container native /tmp (local fast storage).
        export TRITON_CACHE_DIR=/tmp/triton_${SLURM_LOCALID}
        export TORCHINDUCTOR_CACHE_DIR=/tmp/inductor_${SLURM_LOCALID}
        mkdir -p ${TRITON_CACHE_DIR} ${TORCHINDUCTOR_CACHE_DIR}

        # Pre-stage: warm local cache from NFS (one rank per node)
        if [[ "${SLURM_LOCALID}" == "0" ]]; then
            if [[ -d "${NFS_TRITON_CACHE}" ]]; then
                echo "Pre-staging triton cache from NFS..."
                rsync -a --ignore-existing "${NFS_TRITON_CACHE}/" "${TRITON_CACHE_DIR}/" 2>/dev/null || true
            fi
            if [[ -d "${NFS_INDUCTOR_CACHE}" ]]; then
                echo "Pre-staging inductor cache from NFS..."
                rsync -a --ignore-existing "${NFS_INDUCTOR_CACHE}/" "${TORCHINDUCTOR_CACHE_DIR}/" 2>/dev/null || true
            fi
        fi

        # Post-stage: write back to NFS on exit (one rank per node)
        _stage_back() {
            if [[ "${SLURM_LOCALID}" == "0" ]]; then
                echo "Staging triton cache back to NFS..."
                mkdir -p "${NFS_TRITON_CACHE}" "${NFS_INDUCTOR_CACHE}"
                rsync -a --ignore-existing "${TRITON_CACHE_DIR}/" "${NFS_TRITON_CACHE}/" 2>/dev/null || true
                rsync -a --ignore-existing "${TORCHINDUCTOR_CACHE_DIR}/" "${NFS_INDUCTOR_CACHE}/" 2>/dev/null || true
                echo "Cache staged back."
            fi
        }
        trap _stage_back EXIT

        # Checkpoint directory — node-local /tmp (cleaned up by the cleanup job).
        CKPT_DIR=/tmp/ckpt_${SLURM_JOB_ID}
        mkdir -p ${CKPT_DIR}

        if [[ "${USE_FP8:-1}" == "1" ]]; then
            QUANT_ARGS="--fp8-format hybrid \
            --fp8-recipe delayed \
            --fp8-param-gather \
            --fp8-amax-history-len 1024 \
            --fp8-amax-compute-algo max \
            --fp8-margin 0"
        elif [[ "${USE_FP4:-0}" == "1" ]]; then
            QUANT_ARGS="--fp4-format e2m1 \
            --fp4-recipe nvfp4"
        else
            QUANT_ARGS=""
        fi

        if [[ "${USE_OVERLAP_COMM:-0}" == "1" ]]; then
            OVERLAP_ARGS="--overlap-grad-reduce --overlap-param-gather"
        else
            OVERLAP_ARGS=""
        fi

        # Build checkpoint args (controlled by USE_ASYNC_CKPT from .myenv).
        # No --load: we only want to test save here.
        CKPT_SAVE_ARGS=""
        if [[ "${USE_ASYNC_CKPT}" == "1" ]]; then
            CKPT_SAVE_ARGS="--save ${CKPT_DIR} --save-interval ${CKPT_SAVE_INTERVAL} --async-save --use-persistent-ckpt-worker --use-dist-ckpt --ckpt-fully-parallel-save --ckpt-assume-constant-structure $([[ "${USE_CPU_SHM}" == "1" ]] && echo "--async-ckpt-use-cpu-shm")"
        fi

        pushd $MEGATRON_PATH
        LAUNCHER_CMD="python3"
        LAUNCHER_ARGS=" \
        "
        WORKLOAD_CMD=${MEGATRON_PATH}/pretrain_gpt.py
        WORKLOAD_ARGS=" \
            --exit-duration-in-mins 5750 \
            --distributed-timeout-minutes 10 \
            --disable-gloo-process-groups \
            --mock-data \
            --data-cache-path /datacache \
            --no-create-attention-mask-in-dataloader \
            --no-mmap-bin-files \
            --tokenizer-type NullTokenizer \
            --tiktoken-pattern v2 \
            --tokenizer-model /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/nemotron6/tokenizers/multiMixV8.gpt4o_nc_sd.500000.128k.vocab.json \
            --micro-batch-size 1 \
            --global-batch-size 64 \
            --train-samples 10240000 \
            --adam-beta1 0.9 \
            --adam-beta2 0.95 \
            --adam-eps 1e-05 \
            --lr-decay-style cosine \
            --lr-warmup-samples 1024000 \
            --lr-decay-samples 20480000 \
            --lr 0.0003 \
            --min-lr 2.9999999999999997e-05 \
            --weight-decay 0.1 \
            --clip-grad 1.0 \
            --loss-scale 1.0 \
            --use-mcore-models \
            --untie-embeddings-and-output-weights \
            --disable-bias-linear \
            --attention-backend flash \
            --transformer-impl transformer_engine \
            --position-embedding-type rope \
            --rotary-base 500000 \
            --rotary-interleaved \
            --use-rope-scaling \
            --rope-scaling-factor 8.0 \
            --no-rope-fusion \
            --no-rope-freq 4 \
            --use-flash-attn \
            --cross-entropy-fusion-impl te \
            --cross-entropy-loss-fusion \
            --seq-length 8192 \
            --max-position-embeddings 8192 \
            --num-layers 12 \
            --swiglu \
            --hidden-size 5120 \
            --num-attention-heads 40 \
            --group-query-attention \
            --num-query-groups 8 \
            --ffn-hidden-size 16384 \
            --kv-channels 128 \
            --normalization RMSNorm \
            --attention-dropout 0.0 \
            --hidden-dropout 0.0 \
            --grad-reduce-in-bf16 \
            --qk-l2-norm \
            --num-experts 16 \
            --moe-layer-freq 1 \
            --moe-ffn-hidden-size 8192 \
            --moe-shared-expert-intermediate-size 8192 \
            --moe-router-topk 1 \
            --moe-router-score-function sigmoid \
            --moe-token-dispatcher-type alltoall \
            --moe-grouped-gemm \
            --moe-shared-expert-overlap \
            --moe-router-bias-update-rate 0.001 \
            --moe-router-load-balancing-type aux_loss \
            --moe-aux-loss-coeff 0.01 \
            --moe-router-enable-expert-bias \
            --moe-apply-probs-on-input \
            --moe-router-force-load-balancing \
            --bf16 \
            ${QUANT_ARGS} \
            --te-rng-tracker \
            --sequence-parallel \
            --use-distributed-optimizer \
            ${OVERLAP_ARGS} \
            --ddp-num-buckets 5 \
            --tensor-model-parallel-size 1 \
            --pipeline-model-parallel-size 1 \
            --expert-model-parallel-size 8 \
            --expert-tensor-parallel-size 1 \
            --ddp-average-in-collective \
            --log-interval 1 \
            --timing-log-option minmax \
            --log-params-norm \
            --log-num-zeros-in-grad \
            --log-throughput \
            --check-weight-hash-across-dp-replicas-interval 20000 \
            --tensorboard-dir /tensorboard \
            --logging-level 10 \
            --eval-iters 14 \
            --eval-interval 2000 \
            --manual-gc \
            --manual-gc-interval 100 \
            --num-workers 1 \
            --local-rank ${SLURM_LOCALID} \
            --context-parallel-size 1 \
            --vocab-size 238600 \
            --distributed-timeout-seconds-after-init ${DIST_TIMEOUT_AFTER_INIT} \
            --flight-recorder-dump-path /flight_recorder \
        "
        $LAUNCHER_CMD $LAUNCHER_ARGS $WORKLOAD_CMD $WORKLOAD_ARGS $CKPT_SAVE_ARGS
    '
log_msg "END main_workload"

log_msg "END SBATCH"

set +x
