# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/nvhcd.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/nvhcd.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/nvhcd.proto\x12\x05nvhcd\"\"\n\x12HealthCheckRequest\x12\x0c\n\x04\x61rgs\x18\x01 \x03(\t\"X\n\x13HealthCheckResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\texit_code\x18\x02 \x01(\x05\x12\x0e\n\x06output\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t2]\n\x12HealthCheckService\x12G\n\x0eRunHealthCheck\x12\x19.nvhcd.HealthCheckRequest\x1a\x1a.nvhcd.HealthCheckResponseB\x18Z\x16nvhcd.nvidia.com/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.nvhcd_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\026nvhcd.nvidia.com/proto'
  _globals['_HEALTHCHECKREQUEST']._serialized_start=28
  _globals['_HEALTHCHECKREQUEST']._serialized_end=62
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=64
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=152
  _globals['_HEALTHCHECKSERVICE']._serialized_start=154
  _globals['_HEALTHCHECKSERVICE']._serialized_end=247
# @@protoc_insertion_point(module_scope)
