# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import nvhcd_pb2 as proto_dot_nvhcd__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/nvhcd_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HealthCheckServiceStub(object):
    """HealthCheckService provides health check functionality for compute nodes
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunHealthCheck = channel.unary_unary(
                '/nvhcd.HealthCheckService/RunHealthCheck',
                request_serializer=proto_dot_nvhcd__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=proto_dot_nvhcd__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class HealthCheckServiceServicer(object):
    """HealthCheckService provides health check functionality for compute nodes
    """

    def RunHealthCheck(self, request, context):
        """RunHealthCheck executes the configured health check script with given arguments
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthCheckServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunHealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.RunHealthCheck,
                    request_deserializer=proto_dot_nvhcd__pb2.HealthCheckRequest.FromString,
                    response_serializer=proto_dot_nvhcd__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nvhcd.HealthCheckService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nvhcd.HealthCheckService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HealthCheckService(object):
    """HealthCheckService provides health check functionality for compute nodes
    """

    @staticmethod
    def RunHealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nvhcd.HealthCheckService/RunHealthCheck',
            proto_dot_nvhcd__pb2.HealthCheckRequest.SerializeToString,
            proto_dot_nvhcd__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
