name: Trigger GitLab CI/CD

on:
  push:
    branches:
      - test-ci
  pull_request:
    branches:
      - test-ci

jobs:
  trigger-gitlab:
    # Uses the source branch of the PR to trigger GitLab CI.
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab Pipeline
        run: |
          curl --request POST \
               --fail \
               --form "token=${{ secrets.GITLAB_TRIGGER_TOKEN }}" \
               --form "ref=${{ github.head_ref }}" \
               "https://gitlab-master.nvidia.com/api/v4/projects/171336/trigger/pipeline"
